version: 2
jobs:
  build:
    docker:
      - image: ubuntu:19.10

    steps:
      - checkout

      - run:
          name: Update APT Repos
          command: apt-get update

      - run:
          name: Build Tool Setup (python)
          command: apt-get install -y python3 python3-pip

      - run:
          name: Build Tool Setup (conan)
          command: pip3 install conan cmake && conan config get
      
      - run:
          name: Conan Install 3rd Party Dependencies
          command: mkdir build && cd build && conan install ..
      
      - run:
          name: CMake Setup
          command: cd build && cmake ..
      
      - run:
          name: Compile
          command: cd build && make
      
      - run:
          name: CTest
          command: cd build && make test